# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'FWCommponents' do
    
    # FW系列UI库
    
    # 分段控件：https://github.com/choiceyou/FWSegmentedControl
    pod 'FWSegmentedControl'
    
    # 弹窗控件：https://github.com/choiceyou/FWPopupView
    pod 'FWPopupView'
    
    # 轮播控件：https://github.com/choiceyou/FWCycleScrollView
    pod 'FWCycleScrollView'
    
    # 侧滑控件：https://github.com/choiceyou/FWSideMenu
    pod 'FWSideMenu'
    
    
    # Rx相关
    
    # https://github.com/ReactiveX/RxSwift
    pod 'RxSwift'
    pod 'RxCocoa'
    
    # https://github.com/RxSwiftCommunity/NSObject-Rx
    pod 'NSObject+Rx'
    
    
    # 其他
    
    # Swift版的Masonry：https://github.com/SnapKit/SnapKit
    pod 'SnapKit'
    
    # 下拉刷新：https://github.com/CoderMJLee/MJRefresh
    pod 'MJRefresh'
    
    # JSON解析：https://github.com/SwiftyJSON/SwiftyJSON
    pod 'SwiftyJSON'
    
    # JSON解析：https://github.com/alibaba/HandyJSON
    pod 'HandyJSON'
    
end
