# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'FWCommponents' do
    
    pod 'FWSegmentedControl'
    pod 'FWPopupView'
    pod 'FWCycleScrollView'
    pod 'FWSideMenu'
    
end
